### ISSUE TITLE
Aliceblue Holding Issue 

### ISSUE THREAD

**Issue by crypt0inf0** [marketcalls/openalgo#116]
While visiting holding section I get the following error

```
b'{"stat":"Ok","clientid":"","HoldingVal":[{"WCqty":"0","BSEHOldingValue":"65.49","hsflag":"Y","Series1":"E","HUqty":"1","authQty":"0","YSXHOldingValue":"0.00","CSEHOldingValue":"0.00","Ttrind":"N","DaysMTM":"0","csflag":"N","WHqty":"0","Pcode":"CNC","Price":"50.28","BuyQty":"0","Exch4":"0","Bsetsym":"GOLDBEES","Exch5":"0","LTcse":"0.00","MCXHOldingValue":"0.00","Holdqty":"0","Exch1":"nse_cm","Exch2":"bse_cm","Exch3":"0","LTysx":"0.00","Haircut":"0.00","Scripcode":"590095","LTPValuation":"0","NSEHOldingValue":"65.49","Ysxtsym":"0","Ltp":"65.53","Coltype":"--","Btst":"0","LTmcxsxcm":"0.00","Usedqty":"0","poaStatus":"N","Token5":"0","Nsetsym":"GOLDBEES-EQ","CUqty":"0","Token2":"590095","Token1":"14428","Token4":"0","SellableQty":"1","Token3":"0","Mcxsxcmsym":"0","Csetsym":"0","authFlag":false,"LTnse":"65.49","pdc":"65.53","Series":"EQ","Colqty":"0","ExchSeg5":null,"ExchSeg2":"BSE","ExchSeg1":"NSE","ExchSeg4":null,"LTbse":"65.53","ExchSeg3":null,"isin":"INF204KB17I5","Tprod":"NA"}],"Totalval":{"TotalMCXHoldingValue":"0.00","TotalCSEHoldingValue":"0.00","TotalNSEHoldingValue":"65.49","TotalYSXHoldingValue":"0.00","TotalBSEHoldingValue":"65.49"}}'
{'stat': 'Ok', 'clientid': '', 'HoldingVal': [{'WCqty': '0', 'BSEHOldingValue': '65.49', 'hsflag': 'Y', 'Series1': 'E', 'HUqty': '1', 'authQty': '0', 'YSXHOldingValue': '0.00', 'CSEHOldingValue': '0.00', 'Ttrind': 'N', 'DaysMTM': '0', 'csflag': 'N', 'WHqty': '0', 'Pcode': 'CNC', 'Price': '50.28', 'BuyQty': '0', 'Exch4': '0', 'Bsetsym': 'GOLDBEES', 'Exch5': '0', 'LTcse': '0.00', 'MCXHOldingValue': '0.00', 'Holdqty': '0', 'Exch1': 'nse_cm', 'Exch2': 'bse_cm', 'Exch3': '0', 'LTysx': '0.00', 'Haircut': '0.00', 'Scripcode': '590095', 'LTPValuation': '0', 'NSEHOldingValue': '65.49', 'Ysxtsym': '0', 'Ltp': '65.53', 'Coltype': '--', 'Btst': '0', 'LTmcxsxcm': '0.00', 'Usedqty': '0', 'poaStatus': 'N', 'Token5': '0', 'Nsetsym': 'GOLDBEES-EQ', 'CUqty': '0', 'Token2': '590095', 'Token1': '14428', 'Token4': '0', 'SellableQty': '1', 'Token3': '0', 'Mcxsxcmsym': '0', 'Csetsym': '0', 'authFlag': False, 'LTnse': '65.49', 'pdc': '65.53', 'Series': 'EQ', 'Colqty': '0', 'ExchSeg5': None, 'ExchSeg2': 'BSE', 'ExchSeg1': 'NSE', 'ExchSeg4': None, 'LTbse': '65.53', 'ExchSeg3': None, 'isin': 'INF204KB17I5', 'Tprod': 'NA'}], 'Totalval': {'TotalMCXHoldingValue': '0.00', 'TotalCSEHoldingValue': '0.00', 'TotalNSEHoldingValue': '65.49', 'TotalYSXHoldingValue': '0.00', 'TotalBSEHoldingValue': '65.49'}}
ERROR:app:Exception on /holdings [GET]
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/openalgo/utils/session.py", line 77, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/workspaces/openalgo/blueprints/orders.py", line 190, in holdings
    holdings_data = map_portfolio_data(holdings_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/openalgo/broker/aliceblue/mapping/order_data.py", line 316, in map_portfolio_data
    if portfolio['Pcode'] == 'CNC':
       ~~~~~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'
INFO:werkzeug:127.0.0.1 - - [13/Dec/2024 16:59:24] "GET /holdings HTTP/1.1" 500 -```

**Comment by marketcalls** [comment]
Do you have any active holdings right now?

**Comment by marketcalls** [comment]
Now the Aliceblue Holding issue is fixed!
Closing the access.
