### ISSUE TITLE
Single legged orders are getting affected in SMART_ORDER

### ISSUE THREAD

**Issue by tradewithmadhan** [marketcalls/openalgo#154]
![image](https://github.com/user-attachments/assets/b2dd8a7c-2577-4abd-978b-c611c4bc62db)

![image](https://github.com/user-attachments/assets/d2a4478c-703d-4bfb-b696-c915c8c2ec68)

Hi , Single legged orders are getting affected by this setting . when we place smart order for Fut/options with multiple leg then only the delay should have ...

Request you to please check and fix it ...  in above snap i placed order for a stock which is always have single leg but in current code there is the delay before place order ...

**Comment by marketcalls** [comment]
There are actually two potential sources of delay in the smart order flow:

1. Pre-Order Position Check:
   - Smart orders first fetch the current positions to determine what orders to place
   - This requires an API call to the position book
   - The delay here depends on:
     - Network latency
     - Broker's API response time
     - Time to process position data

2. Configured Post-Order Delay:
   - The `SMART_ORDER_DELAY` setting (default 0.5s)
   - Happens after order placement
   - Configurable through .env file

If you're experiencing significant delays, it could be due to the position book API call rather than just the configured delay. The position check is necessary for smart order logic to work correctly, but it does add some latency to the process.

Recommendations:
1. Monitor the broker's position API response times
2. Adjust `SMART_ORDER_DELAY` based on your needs, but be aware it's not the only source of latency

**Comment by marketcalls** [comment]
### Update - Fixed in Latest Release

I've published a new release that addresses the logging timestamp issue. Here are the key changes:

1. **Fixed Order Logging Sequence**
   - Order logs are now written immediately after order placement
   - Timestamps in logs now accurately reflect when orders were sent to the broker
   - The configured delay (SMART_ORDER_DELAY) no longer affects the logged timestamp

2. **Clarification on Delays**
   The smart order process has two types of delays:
   - Position check delay (before order placement) - Required API call to check current positions
   - Configured SMART_ORDER_DELAY (after order placement) - Configurable rate limiting

3. **More Accurate Timestamps**
   - Previous: Timestamps included both position check and configured delays
   - Now: Timestamps reflect actual order placement time

This change gives you more accurate data for order timing analysis while maintaining the rate limiting protection. The SMART_ORDER_DELAY still applies before sending the response, but it no longer affects the logged timestamps.

Please update to the latest version to get these improvements.

**Comment by marketcalls** [comment]
are you sending orders via ngrok? If yes then such delay is expected
Read more here https://docs.openalgo.in/latency

Alternative is to use VPS/Cloud servers at Mumbai Datacenters to reduce latency.

**Comment by shivjanaa** [comment]
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.


 finvesia broker

* Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug:127.0.0.1 - - [21/Jan/2025 22:05:38] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Jan/2025 22:05:38] "GET /static/favicon/logo.png HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Jan/2025 22:05:38] "GET /static/js/theme.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Jan/2025 22:05:38] "GET /static/css/main.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Jan/2025 22:05:38] "GET /static/sounds/alert.mp3 HTTP/1.1" 206 -
INFO:werkzeug:127.0.0.1 - - [21/Jan/2025 22:05:41] "GET /static/favicon/site.webmanifest HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Jan/2025 22:05:49] "GET /auth/login HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [21/Jan/2025 22:05:49] "GET /auth/broker HTTP/1.1" 302 -
ERROR:app:Exception on /dashboard [GET]
Traceback (most recent call last):
  File "c:\Users\namit\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\namit\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\namit\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "c:\Users\namit\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "c:\Users\namit\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\namit\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]     
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Users\namit\OneDrive\Desktop\openalgo\utils\session.py", line 77, in decorated_function
    return f(*args, **kwargs)
  File "c:\Users\namit\OneDrive\Desktop\openalgo\blueprints\dashboard.py", line 44, in dashboard
    margin_data = get_margin_data_func(AUTH_TOKEN)
  File "c:\Users\namit\OneDrive\Desktop\openalgo\broker\shoonya\api\funds.py", line 34, in get_margin_data      
    conn.request("POST", "/NorenWClientTP/Limits", payload, headers)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\namit\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1336, in request       
    self._send_request(method, url, body, headers, encode_chunked)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\namit\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1382, in _send_request 
    self.endheaders(body, encode_chunked=encode_chunked)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\namit\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1331, in endheaders    
    self._send_output(message_body, encode_chunked=encode_chunked)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\namit\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1091, in _send_output  
    self.send(msg)
    ~~~~~~~~~^^^^^
  File "c:\Users\namit\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1035, in send
    self.connect()
    ~~~~~~~~~~~~^^
  File "c:\Users\namit\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1477, in connect       
    self.sock = self._context.wrap_socket(self.sock,
                ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
                                          server_hostname=server_hostname)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\namit\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\namit\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "c:\Users\namit\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1018)
INFO:werkzeug:127.0.0.1 - - [21/Jan/2025 22:05:50] "GET /dashboard HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Jan/2025 22:05:50] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by marketcalls** [comment]
Hi Iam seeing that you are getting ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED]

in that case consider implementing this workaround to fix this issue.
https://docs.openalgo.in/getting-started/windows-installation/ssl-verification-failed

**Comment by marketcalls** [comment]
closing the ticket as the first order is likely will not take time however second order takes a delay as we are currently sing SMART_ORDER_DELAY feature to avoid hitting the broker rate limits
